<?php

return [
    'title' => 'Team',
    'sub_title' => 'Management',
    'description' => 'Vitalentra Group International is supported by an experienced professional team committed to innovation and quality. Together with strategic partners such as Ippho Santosa, we present trusted and sustainable healthy solutions.',
     'content' => [
        '1' => 'As President Commissioner at Vitalentra Group International, Marida brings over 15 years of experience in finance and distribution. A graduate in Accounting from STIE Kusuma Negara, she began her career as Finance & Administration Manager at PT Dayatama Trimitra for over a decade. Since 2017, she has been the main distributor for British Propolis Group and has successfully achieved the title of Top Sales Distributor for seven consecutive years.<br/>Her contributions and leadership are not only reflected in her impressive sales figures but also in her ability to identify market opportunities and ensure business sustainability. Under her strategic oversight, Vitalentra continues to strengthen its commitment to delivering quality and trusted products to Indonesian consumers.',
         '2' => "<p>Beka Masinggil is the Commissioner of Vitalentra Group International and an experienced leader in business development with over 18 years of leadership experience across various strategic industries, including defense, automotive, electronics, and biofuels. His expertise includes operations management, market development, and the implementation of integrated quality systems.</p><p>His career includes several key positions, starting as Director of Business Development at PT Mandiri Mitra Muhibbah (M-3 Defense Industry), where he led strategic expansion and built relationships with government agencies and international embassies. He has also served as Director of Operations and Management Representative, playing a role in strategic planning and the comprehensive implementation of quality management systems. Early in his career, he developed his competencies at PT Indo Biofuels, Mercedes-Benz Indonesia, and SHARP Electronics Indonesia, including leading national account teams and managing all promotional activities and ordering processes.</p><p>In 2024, Beka expanded his role as Strategic Partner for two entities: GRID EV Charging Technology, focusing on electric vehicle business development, and PT Mandiri Mitra Muhibbah, strengthening strategic partnerships and national defense industry expansion. In 2025, he was also appointed as the Main Commissioner of PT Pasifik Cahaya Nusantara, a telecommunications tower provider focusing on maintenance services.</p><p>Beka holds a Master's degree in International Technology Transfer Management from Berliner Hochschule für Technik (Germany) and a Bachelor's degree in Industrial Engineering from Trisakti University (Indonesia). He has also recently completed a special program in Espionage, Intelligence, and National Security at the University of Oxford (UK).</p><p>Currently, he is also active in various international chambers of commerce and contributes to the Indonesian defense industry ecosystem through the Ministry of Defense.</p>",
        '3' => '<p>With over a decade of experience in sales and distribution, Muhammad Nuzullaiman now leads as President Director of Vitalentra Group International. A graduate in Management Economics from STIE Kusuma Negara, he began his career in production and sales at multinational companies, eventually becoming the main distributor for British Propolis since 2017. His leadership has brought sustainable success, evidenced by the Top Sales Distributor award for seven consecutive years.</p><p>In building Vitalentra, Nuzullaiman believes that health must start with awareness. <i>“We are here to provide products that are not only of high quality but also offer real value to public health,”</i> said the man born on July 25, 1981.</p>',
        '4' => "<p>Tito Masinggil is the Operations Director at Vitalentra Group International, with over 13 years of experience in management and operations. A graduate in Management Economics from Trisakti University, he has worked at PT Ford Motor Indonesia and PT Dayatama Trimitra, before serving as VP of Administration & Finance at PT Mandiri Mitra Muhibbah.</p><p>At Vitalentra, Tito brings a passion for making a positive impact through health products. <i>“Amid the rising cases of diseases such as diabetes, hypertension, and stroke at a young age, I believe Vitalentra products can be a real preventive solution and help people meet their daily nutritional needs,”</i> he said.</p><p>Known for his discipline and commitment to quality, Tito is also active in various organizations and has earned ISO 9001:2015 certification, making him the right person to lead the company’s operations with a greater purpose: health for all.</p>",
        '5' => "<p>Renya Nuringtyas is a corporate communication and public relations professional with over 15 years of experience across various industries, from information technology and services to aviation. A graduate in Communication Science from the University of Indonesia, she has led various strategic communication initiatives at major companies, including Biznet and Qatar Airways, and handled high-profile clients while working at global PR agencies such as Ogilvy PR and Edelman.</p><p>Renya is known for her ability to craft strong and impactful messages, both for internal and external company needs. She previously served as Corporate Communication Manager at Biznet, managing all aspects of corporate communication, from media relations and crisis communication to CSR programs and social media. In addition, she is also active as an independent PR consultant, content writer, and professional translator who has handled various projects in the technology, consumer, parenting, and lifestyle sectors — both in Indonesian and English.</p><p><i>“For me, effective communication is not just about delivering information, but building trust, uniting vision, and touching the emotional side of the audience.”</i></p><p>Now, as Chief Marketing Officer at Vitalentra Group International, Renya plays a key role in building brand narratives, strengthening the company’s position in the supplement and natural care industry, and bridging communication between the company and the public through a strategic and authentic approach.</p>",
    ],
    'commissioner' => 'Commissioner',
];
