<?php

return [
    'title' => 'Team',
    'sub_title' => 'Management',
    'description' => 'Vitalentra Group International is supported by a team of experienced professionals committed to innovation and quality. Together with business partners such as BP Group founded by Ippho Santosa, we deliver trusted and sustainable health solutions.',
    'content' => [
        '1' => "<p>As President Commissioner at Vitalentra Group International, Marida brings over 15 years of experience in finance and distribution. A graduate in Accounting from STIE Kusuma Negara, she began her career as Finance & Administration Manager at PT Dayatama Trimitra for more than a decade. Since 2017, she has been the main distributor for British Propolis Group and has successfully achieved Top Sales Distributor status for seven consecutive years.</p><p>Her achievements and leadership are not only reflected in numbers, but also in her ability to read market opportunities and maintain business sustainability. Under her strategic supervision, Vitalentra continues to strengthen its commitment to delivering quality and trusted products to Indonesian consumers.</p>",
        '2' => "<p>Beka Masinggil is a Commissioner at Vitalentra Group International and an experienced business leader with over 18 years of leadership experience in various strategic sectors, including defense, automotive, electronics, and biofuel. His expertise covers operational management, market development, and the implementation of integrated quality systems.</p><p>His career has been built through various important positions. He currently serves as Director of Business Development at PT Mandiri Mitra Muhibbah (M-3), where he leads strategic expansion and builds close relationships with many government agencies and embassies in Indonesia. At M-3, he has also served as Director of Operations and Management Representative, playing a role in strategic planning and comprehensive quality systems implementation. Early in his career, he built competencies at PT Indo Biofuels, Mercedes-Benz Indonesia, and SHARP Electronics Indonesia, where he was trusted to lead sales and promotion teams and oversee order processes.</p><p>In 2024, Beka expanded his role as Strategic Partner in two entities: GRID EV Charging Technology, focusing on electric vehicle business development, and supporting PT Mandiri Mitra Muhibbah (M-3) in strengthening strategic partnerships and driving national defense industry expansion. In 2025, he is also trusted as President Commissioner of PT Pasifik Cahaya Nusantara, a telecommunications tower provider focused on maintenance services.</p><p>Beka holds a Master’s degree in International Technology Transfer Management from Berliner Hochschule für Technik (Germany) and a Bachelor’s degree in Industrial Engineering from Universitas Trisakti (Indonesia). He recently completed a special program in Espionage, Intelligence, and National Security at the University of Oxford (UK).</p><p>Currently, Beka is active in various international chambers of commerce and contributes to strengthening Indonesia’s defense industry ecosystem.</p>",
        '3' => "<p>With over a decade of experience in sales and distribution, Muhammad Nuzullaiman now serves as President Director of Vitalentra Group International. A graduate in Management Economics from STIE Kusuma Negara, he began his career in production and sales at multinational companies, eventually becoming the main distributor for British Propolis since 2017. His leadership has brought continuous success, proven by the Top Sales Distributor award for seven consecutive years.</p><p>In building Vitalentra, Nuzullaiman believes that health starts with awareness. <blockquote>“We are here to provide products that are not only high quality, but also deliver real value for public health,”</blockquote> said the man born on July 25, 1981.</p>",
        '4' => "<p>Tito Masinggil is the Operations Director at Vitalentra Group International, with over 13 years of experience in management and operations. A graduate in Management Economics from Universitas Trisakti, he has worked at PT Ford Motor Indonesia and PT Dayatama Trimitra, before serving as VP of Administration & Finance at PT Mandiri Mitra Muhibbah.</p><p>At Vitalentra, Tito brings a passion for making a positive impact through health products. <blockquote>“Amid rising cases of diseases such as diabetes, hypertension, and stroke at a young age, I believe Vitalentra products can be a real preventive solution and help people meet their daily nutritional needs,”</blockquote> he said.</p><p>Known for his discipline and commitment to quality, Tito is also active in various organizations and has earned ISO 9001:2015 certification, making him the right figure to lead company operations with a greater purpose: health for all.</p>",
        '5' => "<p>Renya Nuringtyas is a corporate communications and public relations professional with over 15 years of experience across various industries, from information technology and services to aviation. A graduate in Communication Studies from Universitas Indonesia, she has led strategic communication initiatives at major companies, including Biznet and Qatar Airways, and handled renowned clients while working at global PR agencies such as Ogilvy PR and Edelman.</p><p>Renya is known for her ability to craft strong and impactful messages for both internal and external company needs. She has served as Corporate Communication Manager at Biznet, managing all aspects of corporate communications, from media relations and crisis communications to CSR programs and social media. She is also active as an independent PR consultant, content writer, and professional translator, handling various projects in technology, consumer, parenting, and lifestyle sectors.</p><p><blockquote>“For me, effective communication is not just about delivering information, but building trust, uniting visions, and touching the emotional side of the audience.”</blockquote></p><p>Now, as Chief Marketing Officer at Vitalentra Group International, Renya plays a key role in building brand narratives, strengthening the company’s position in the natural supplement and healthcare industry, and bridging communication between the company and the public through strategic and authentic approaches.</p>",
    ],
    'commissioner' => 'Commissioner',
];
