<?php

return [
    'title' => 'Tim',
    'sub_title' => 'Manajemen',
    'description' => 'Vitalentra Group International didukung oleh tim profesional berpengalaman yang berkomitmen pada inovasi dan kualitas. Bersama mitra strategis seperti Ippho Santosa, kami menghadirkan solusi sehat yang terpercaya dan berkelanjutan.',
    'content' => [
        '1' => "<p>Sebagai President Commissioner di Vitalentra Group International, Marida membawa pengalaman lebih dari 15 tahun dalam dunia keuangan dan distribusi. Lulusan Akuntansi dari STIE Kusuma Negara ini memulai kariernya sebagai Finance & Administration Manager di PT Dayatama Trimitra selama lebih dari satu dekade. Sejak 2017, ia menjadi distributor utama British Propolis Group dan sukses meraih predikat Top Sales Distributor selama tujuh tahun berturut-turut.</p><p>Kiprah dan kepemimpinannya tak hanya terletak pada pencapaian angka, namun juga pada kemampuannya membaca peluang pasar dan menjaga keberlanjutan bisnis. Di bawah pengawasan strategisnya, Vitalentra terus memperkuat komitmennya menghadirkan produk berkualitas dan terpercaya bagi konsumen Indonesia.</p>",
        '2' => "<p>Beka Masinggil adalah Commissioner Vitalentra Group International, yang juga merupakan seorang pemimpin berpengalaman dalam pengembangan bisnis dengan lebih dari 18 tahun rekam jejak kepemimpinan di berbagai industri strategis, termasuk pertahanan, otomotif, elektronik, dan biofuel. Keahliannya mencakup manajemen operasi, pengembangan pasar, dan implementasi sistem mutu yang terintegrasi.</p><p>Kariernya mencakup berbagai posisi penting, mulai dari Director of Business Development di PT Mandiri Mitra Muhibbah (M-3 Defense Industry), di mana ia memimpin ekspansi strategis dan menjalin relasi dengan instansi pemerintahan serta kedutaan internasional. Ia juga pernah menjabat sebagai Director of Operations dan Management Representative, berperan dalam perencanaan strategis serta implementasi sistem manajemen mutu secara menyeluruh. Di awal karier, ia mengembangkan kompetensinya di PT Indo Biofuels, Mercedes-Benz Indonesia, dan SHARP Electronics Indonesia, termasuk memimpin tim akun nasional dan mengelola seluruh aktivitas promosi serta proses pemesanan.</p><p>Pada tahun 2024, Beka memperluas perannya sebagai Strategic Partner untuk dua entitas: GRID EV Charging Technology, dengan fokus pada pengembangan bisnis kendaraan listrik, serta PT Mandiri Mitra Muhibbah, memperkuat kemitraan strategis dan ekspansi industri pertahanan nasional. Di tahun 2025, ia juga dipercaya sebagai Commissioner Utama PT Pasifik Cahaya Nusantara, perusahaan penyedia menara telekomunikasi dengan fokus pada layanan pemeliharaan.</p><p>Beka meraih gelar Magister Manajemen Transfer Teknologi Internasional dari Berliner Hochschule für Technik (Jerman) dan Sarjana Teknik Industri dari Universitas Trisakti (Indonesia). Ia juga baru saja menyelesaikan program khusus di bidang Espionase, Intelijen, dan Keamanan Nasional di University of Oxford (UK).</p><p>Saat ini, ia juga aktif dalam berbagai kamar dagang internasional dan berkontribusi pada ekosistem industri pertahanan Indonesia melalui Kementerian Pertahanan.</p>",
        '3' => "<p>Dengan pengalaman lebih dari satu dekade di industri penjualan dan distribusi, Muhammad Nuzullaiman kini memimpin sebagai President Director Vitalentra Group International. Lulusan Ekonomi Manajemen dari STIE Kusuma Negara ini mengawali karirnya di bidang produksi dan penjualan di perusahaan multinasional, hingga akhirnya menjadi distributor utama British Propolis sejak 2017. Kepemimpinannya membawa kesuksesan berkelanjutan, terbukti dengan penghargaan Top Sales Distributor selama tujuh tahun berturut-turut.</p><p>Dalam membangun Vitalentra, Nuzullaiman percaya bahwa kesehatan harus dimulai dari kesadaran. <i>“Kami hadir untuk menyediakan produk yang bukan hanya berkualitas, tapi juga memberikan nilai nyata bagi kesehatan masyarakat,”</i> ujar pria kelahiran 25 Juli 1981 ini.</p>",
        '4' => "<p>Tito Masinggil adalah Direktur Operasional di Vitalentra Group International, dengan pengalaman lebih dari 13 tahun di bidang manajemen dan operasional. Lulusan Manajemen Ekonomi Universitas Trisakti ini pernah berkarir di PT Ford Motor Indonesia dan PT Dayatama Trimitra, sebelum menjabat sebagai VP Administrasi & Keuangan di PT Mandiri Mitra Muhibbah.</p><p>Di Vitalentra, Tito membawa semangat untuk memberikan dampak positif melalui produk kesehatan. <i>“Di tengah meningkatnya kasus penyakit seperti diabetes, hipertensi, dan stroke di usia muda, saya percaya produk Vitalentra dapat menjadi solusi pencegahan yang nyata dan membantu masyarakat memenuhi kebutuhan nutrisi harian,”</i> ungkapnya.</p><p>Dikenal sebagai pribadi disiplin dan berkomitmen pada kualitas, Tito juga aktif dalam berbagai organisasi dan pernah meraih sertifikasi ISO 9001:2015, menjadikannya sosok yang tepat untuk memimpin operasional perusahaan dengan tujuan yang lebih besar: kesehatan untuk semua.</p>",
        '5' => "<p>Renya Nuringtyas adalah seorang profesional komunikasi korporat dan public relations dengan lebih dari 15 tahun pengalaman di berbagai industri, mulai dari teknologi informasi, layanan, hingga penerbangan. Lulusan Ilmu Komunikasi dari Universitas Indonesia ini telah memimpin berbagai inisiatif komunikasi strategis di perusahaan-perusahaan besar, termasuk Biznet dan Qatar Airways, serta menangani klien-klien ternama saat berkarier di agensi PR global seperti Ogilvy PR dan Edelman.</p><p>Renya dikenal atas kemampuannya menyusun pesan yang kuat dan berdampak, baik untuk kebutuhan internal maupun eksternal perusahaan. Ia pernah menjabat sebagai Corporate Communication Manager Biznet, mengelola seluruh aspek komunikasi perusahaan, mulai dari hubungan media, komunikasi krisis, hingga program CSR dan sosial media. Selain itu, ia juga aktif sebagai konsultan PR independen, penulis konten, serta penerjemah profesional yang telah menangani berbagai proyek di sektor teknologi, konsumer, parenting, dan gaya hidup — baik dalam Bahasa Indonesia maupun Bahasa Inggris.</p><p><i>“Bagi saya, komunikasi yang efektif bukan sekadar menyampaikan informasi, tapi membangun kepercayaan, menyatukan visi, dan menyentuh sisi emosional audiens.”</i></p><p>Kini, sebagai Chief Marketing Officer di Vitalentra Group International, Renya memainkan peran penting dalam membangun narasi brand, memperkuat posisi perusahaan di industri suplemen dan perawatan alami, serta menjembatani komunikasi antara perusahaan dan publik melalui pendekatan yang strategis dan autentik.</p>",
    ],
    'commissioner' => 'Commissioner',
];
