<?php

return [
    'title' => 'Tim',
    'sub_title' => 'Manajemen',
    'description' => 'Vitalentra Group International didukung oleh tim profesional berpengalaman yang berkomitmen pada inovasi dan kualitas. Bersama mitra bisnis seperti BP Group yang didirikan oleh Ippho Santosa, kami menghadirkan solusi sehat yang terpercaya dan berkelanjutan.',
    'content' => [
        '1' => "<p>Sebagai President Commissioner di Vitalentra Group International, Marida membawa pengalaman lebih dari 15 tahun dalam dunia keuangan dan distribusi. Lulusan Akuntansi dari STIE Kusuma Negara ini memulai kariernya sebagai Finance & Administration Manager di PT Dayatama Trimitra selama lebih dari satu dekade. Sejak 2017, ia menjadi distributor utama British Propolis Group dan sukses meraih predikat Top Sales Distributor selama tujuh tahun berturut-turut.</p><p>Kiprah dan kepemimpinannya tak hanya terletak pada pencapaian angka, namun juga pada kemampuannya membaca peluang pasar dan menjaga keberlanjutan bisnis. Di bawah pengawasan strategisnya, Vitalentra terus memperkuat komitmennya menghadirkan produk berkualitas dan terpercaya bagi konsumen Indonesia.</p>",
        '2' => "<p>Beka Masinggil merupakan Komisaris Vitalentra Group International sekaligus business leader berpengalaman dengan lebih dari 18 tahun pengalaman dalam bidang kepemimpinan di berbagai sektor strategis, termasuk pertahanan, otomotif, elektronik, hingga biofuel. Keahliannya mencakup manajemen operasional, pengembangan pasar, serta penerapan integrated quality systems.</p><p>Kariernya dibangun melalui berbagai posisi penting. Saat ini menjabat sebagai Director of Business Development di PT Mandiri Mitra Muhibbah (M-3), dimana ia memimpin ekspansi strategis serta menjalin hubungan erat dengan banyak lembaga pemerintahan dan kantor kedutaan berbagai negara di Indonesia. Di M-3, Ia juga pernah menjabat sebagai Director of Operations dan Management Representative, dimana ia berperan dalam perencanaan strategis serta penerapan quality systems secara menyeluruh. Di awal perjalanan kariernya, ia juga pernah membangun kompetensi di PT Indo Biofuels, Mercedes-Benz Indonesia, dan SHARP Electronics Indonesia, dimana ia dipercaya memimpin tim sales, promotion, dan mengawasi proses pemesanan.</p><p>Pada tahun 2024, Beka memperluas kiprahnya sebagai Strategic Partner di dua entitas yaitu GRID EV Charging Technology, dengan fokus pada pengembangan bisnis kendaraan listrik, serta mendukung PT Mandiri Mitra Muhibbah (M-3) dalam memperkuat kemitraan strategis dan mendorong ekspansi industri pertahanan nasional. Di tahun 2025, ia juga dipercaya menjabat sebagai Komisaris Utama PT Pasifik Cahaya Nusantara, perusahaan penyedia menara telekomunikasi yang berfokus pada layanan pemeliharaan.</p><p>Beka meraih gelar Magister Manajemen Transfer Teknologi Internasional dari Berliner Hochschule für Technik (Jerman) dan Sarjana Teknik Industri dari Universitas Trisakti (Indonesia). Ia juga baru saja menyelesaikan program khusus di bidang Espionase, Intelijen, dan Keamanan Nasional di University of Oxford (UK).</p><p>Saat ini, Beka aktif dalam berbagai kamar dagang internasional serta berkontribusi bagi penguatan ekosistem industri pertahanan Indonesia.</p>",
        '3' => "<p>Dengan pengalaman lebih dari satu dekade di industri penjualan dan distribusi, Muhammad Nuzullaiman kini memimpin sebagai President Director Vitalentra Group International. Lulusan Ekonomi Manajemen dari STIE Kusuma Negara ini mengawali karirnya di bidang produksi dan penjualan di perusahaan multinasional, hingga akhirnya menjadi distributor utama British Propolis sejak 2017. Kepemimpinannya membawa kesuksesan berkelanjutan, terbukti dengan penghargaan Top Sales Distributor selama tujuh tahun berturut-turut.</p><p>Dalam membangun Vitalentra, Nuzullaiman percaya bahwa kesehatan harus dimulai dari kesadaran. <blockquote>“Kami hadir untuk menyediakan produk yang bukan hanya berkualitas, tapi juga memberikan nilai nyata bagi kesehatan masyarakat,”</blockquote> ujar pria kelahiran 25 Juli 1981 ini.</p>",
        '4' => "<p>Tito Masinggil adalah Direktur Operasional di Vitalentra Group International, dengan pengalaman lebih dari 13 tahun di bidang manajemen dan operasional. Lulusan Manajemen Ekonomi Universitas Trisakti ini pernah berkarir di PT Ford Motor Indonesia dan PT Dayatama Trimitra, sebelum menjabat sebagai VP Administrasi & Keuangan di PT Mandiri Mitra Muhibbah.</p><p>Di Vitalentra, Tito membawa semangat untuk memberikan dampak positif melalui produk kesehatan. <blockquote>“Di tengah meningkatnya kasus penyakit seperti diabetes, hipertensi, dan stroke di usia muda, saya percaya produk Vitalentra dapat menjadi solusi pencegahan yang nyata dan membantu masyarakat memenuhi kebutuhan nutrisi harian,”</blockquote> ungkapnya.</p><p>Dikenal sebagai pribadi disiplin dan berkomitmen pada kualitas, Tito juga aktif dalam berbagai organisasi dan pernah meraih sertifikasi ISO 9001:2015, menjadikannya sosok yang tepat untuk memimpin operasional perusahaan dengan tujuan yang lebih besar: kesehatan untuk semua.</p>",
        '5' => "<p>Renya Nuringtyas adalah seorang profesional corporate communications dan public relations dengan lebih dari 15 tahun pengalaman di berbagai industri, mulai dari teknologi informasi, layanan, hingga penerbangan. Lulusan Ilmu Komunikasi dari Universitas Indonesia ini telah memimpin berbagai inisiatif komunikasi strategis di perusahaan-perusahaan besar, termasuk Biznet dan Qatar Airways, serta menangani klien-klien ternama saat berkarier di agensi PR global seperti Ogilvy PR dan Edelman.</p><p>Renya dikenal atas kemampuannya menyusun pesan yang kuat dan berdampak, baik untuk kebutuhan internal maupun eksternal perusahaan. Ia pernah menjabat sebagai Corporate Communication Manager Biznet, mengelola seluruh aspek komunikasi perusahaan, mulai dari media relations, crisis communications, hingga program CSR dan sosial media. Selain itu, ia juga aktif sebagai konsultan PR independen, penulis konten, serta penerjemah profesional yang telah menangani berbagai proyek di sektor teknologi, konsumer, parenting, dan gaya hidup.</p><p><blockquote>“Bagi saya, komunikasi yang efektif bukan sekadar menyampaikan informasi, tapi membangun kepercayaan, menyatukan visi, dan menyentuh sisi emosional audiens.”</blockquote></p><p>Kini, sebagai Chief Marketing Officer di Vitalentra Group International, Renya memainkan peran penting dalam membangun narasi brand, memperkuat posisi perusahaan di industri suplemen dan perawatan kesehatan alami, serta menjembatani komunikasi antara perusahaan dan publik melalui pendekatan yang strategis dan autentik.</p>",
    ],
    'commissioner' => 'Commissioner',
];
